const arrayAllFilm = [
  {
    poster_path:
      'https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
    adult: false,
    backdrop_path: '/jMWkd0fuwbG39eJpzycJzPWMCww.jpg',
    id: 399566,
    vote_count: 2694,
    vote_average: 8.6,
    title: 'Godzilla vs. Kong',
    video: false,
    release_date: '2021',
    genre_ids: [28, 878],
    original_language: 'en',
    overview:
      'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    original_title: 'Godzilla vs. Kong',
    popularity: 22934.813,
    media_type: 'movie',
    genres: [' Action', ' Science Fiction'],
  },
  {
    adult: false,
    backdrop_path: '/5NxjLfs7Bi07bfZCRl9CCnUw7AA.jpg',
    genre_ids: [878, 28, 12, 53],
    id: 412656,
    title: 'Chaos Walking',
    vote_count: 83,
    vote_average: 7.3,
    video: false,
    release_date: '2021',
    overview:
      'Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.',
    original_title: 'Chaos Walking',
    poster_path:
      'https://image.tmdb.org/t/p/w500/3W9EpQCVzOfZmeWDMMEiLdtSKSe.jpg',
    original_language: 'en',
    popularity: 257.19,
    media_type: 'movie',
    genres: [' Science Fiction', ' Action', ' Other'],
  },
  {
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    release_date: '2021',
    adult: false,
    backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
    vote_count: 4332,
    genre_ids: [28, 12, 14, 878],
    vote_average: 8.6,
    original_language: 'en',
    original_title: "Zack Snyder's Justice League",
    poster_path:
      'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
    title: "Zack Snyder's Justice League",
    video: false,
    id: 791373,
    popularity: 8408.992,
    media_type: 'movie',
    genres: [' Action', ' Adventure', ' Other'],
  },
  {
    original_name: 'The Falcon and the Winter Soldier',
    origin_country: ['US'],
    backdrop_path: '/JB17sIsU53NuWVUecOwrCA0CUp.jpg',
    id: 88396,
    vote_count: 2587,
    first_air_date: '2021-03-19',
    name: 'The Falcon and the Winter Soldier',
    vote_average: 7.8,
    genre_ids: [10765, 10759, 18],
    poster_path:
      'https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg',
    original_language: 'en',
    overview:
      'Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.',
    popularity: 5223.212,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'The Falcon and the Winter Soldier',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/zii6DDzh0AQMuf9rhAW2L9E1fOi.jpg',
    genre_ids: [18, 37],
    id: 621954,
    original_language: 'en',
    original_title: 'Concrete Cowboy',
    overview:
      'Sent to live with his estranged father for the summer, a rebellious teen finds kinship in a tight-knit Philadelphia community of Black cowboys.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/qRW2poVt06WCVlIhrolWS5af4YV.jpg',
    release_date: '2020',
    title: 'Concrete Cowboy',
    video: false,
    vote_average: 4.9,
    vote_count: 8,
    popularity: 19.433,
    media_type: 'movie',
    genres: [' Drama', ' Western'],
  },
  {
    adult: false,
    backdrop_path: '/nFfXSe79XsJXkkcXZxcQDwbkBm8.jpg',
    genre_ids: [18],
    id: 660006,
    original_language: 'fr',
    original_title: 'Madame Claude',
    overview:
      'Paris, the late 1960s. Madame Claude is at the head of a flourishing business dedicated to prostitution that gives her power over both the french political and criminal worlds. But the end of her empire is closer than she thinks.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wce7KTNGvhYfJqIgtxMhPWrllzg.jpg',
    release_date: '2021',
    title: 'Madame Claude',
    video: false,
    vote_average: 7,
    vote_count: 2,
    popularity: 38.381,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/vx4bevtt3ZVgezPZsuiVxm90l5E.jpg',
    genre_ids: [53, 80],
    id: 651589,
    original_language: 'es',
    original_title: 'Hasta el cielo',
    overview:
      'A commentary on Spanish society dressed as a thriller about the misadventures of a gang of young petty criminals after the real state crash.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/4wBsYozsXBlG7Lx4NO7ycDWnnUs.jpg',
    release_date: '2020',
    title: 'Sky High',
    video: false,
    vote_average: 6.9,
    vote_count: 18,
    popularity: 29.303,
    media_type: 'movie',
    genres: [' Thriller', ' Crime'],
  },
  {
    name: 'Riverdale',
    original_language: 'en',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg',
    id: 69050,
    vote_average: 8.6,
    overview:
      'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    vote_count: 10821,
    first_air_date: '2017-01-26',
    original_name: 'Riverdale',
    origin_country: ['US'],
    backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
    genre_ids: [9648, 18, 80],
    popularity: 1461.366,
    media_type: 'tv',
    release_date: '2017',
    original_title: 'Riverdale',
    genres: [' Mystery', ' Drama', ' Other'],
  },
  {
    vote_average: 8.3,
    overview:
      'A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.',
    release_date: '2021',
    id: 600354,
    adult: false,
    backdrop_path: '/h3weAFgg06GqchI2xDfufBgSFTj.jpg',
    genre_ids: [18],
    vote_count: 146,
    original_language: 'en',
    original_title: 'The Father',
    poster_path:
      'https://image.tmdb.org/t/p/w500/uxWXW1YYQENSv7OzHB4Hds0bK3b.jpg',
    video: false,
    title: 'The Father',
    popularity: 157.379,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    title: 'Wonder Woman 1984',
    vote_average: 6.8,
    overview:
      'A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.',
    release_date: '2020',
    adult: false,
    backdrop_path: '/egg7KFi18TSQc1s24RMmR9i2zO6.jpg',
    vote_count: 4613,
    genre_ids: [14, 28, 12],
    id: 464052,
    original_language: 'en',
    original_title: 'Wonder Woman 1984',
    poster_path:
      'https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
    video: false,
    popularity: 2278.642,
    media_type: 'movie',
    genres: [' Fantasy', ' Action', ' Other'],
  },
  {
    genre_ids: [35, 10749],
    original_language: 'nl',
    original_title: 'Just Say Yes',
    poster_path:
      'https://image.tmdb.org/t/p/w500/7nn4g3RQ5A4p8n3T43UtZdUAOPF.jpg',
    video: false,
    vote_average: 5.7,
    vote_count: 3,
    overview:
      'Incurable romantic Lotte finds her life upended when her plans for a picture-perfect wedding unravel -- just as her self-absorbed sister gets engaged.',
    id: 802504,
    title: 'Just Say Yes',
    release_date: '2021',
    adult: false,
    backdrop_path: '/zUzwNcd3o6yaE5aVHC2G8eCo3qC.jpg',
    popularity: 43.439,
    media_type: 'movie',
    genres: [' Comedy', ' Romance'],
  },
  {
    vote_average: 8.3,
    overview:
      'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.',
    release_date: '2021',
    id: 527774,
    adult: false,
    backdrop_path: '/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg',
    genre_ids: [16, 12, 14, 10751, 28],
    vote_count: 1943,
    original_language: 'en',
    original_title: 'Raya and the Last Dragon',
    poster_path:
      'https://image.tmdb.org/t/p/w500/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg',
    video: false,
    title: 'Raya and the Last Dragon',
    popularity: 4243.624,
    media_type: 'movie',
    genres: [' Animation', ' Adventure', ' Other'],
  },
  {
    first_air_date: '2021-03-26',
    original_name: 'Invincible',
    origin_country: ['US'],
    overview:
      'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
    backdrop_path: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
    vote_count: 251,
    genre_ids: [16, 10759, 18],
    id: 95557,
    original_language: 'en',
    name: 'Invincible',
    poster_path:
      'https://image.tmdb.org/t/p/w500/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',
    vote_average: 8.8,
    popularity: 546.469,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'Invincible',
    genres: [' Animation', ' Drama'],
  },
  {
    original_name: 'Made For Love',
    origin_country: ['US'],
    genre_ids: [18, 10765, 35],
    id: 90970,
    vote_count: 4,
    first_air_date: '2021-04-01',
    name: 'Made For Love',
    vote_average: 7.5,
    original_language: 'en',
    overview:
      'Thirty-something Hazel Green tries to escape a suffocating marriage — until she realizes her tech billionaire husband has implanted a revolutionary tracking device, the Made for Love, in her brain.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/mfQiuyhFM4Yv98WWV0BTswKG8rM.jpg',
    backdrop_path: '/xKH3vv9sRebArtFTsPJCgX84oEc.jpg',
    popularity: 79.012,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'Made For Love',
    genres: [' Drama', ' Comedy'],
  },
  {
    original_language: 'en',
    poster_path:
      'https://image.tmdb.org/t/p/w500/mZve7vS8S7nyYMIJ5rJrjzOGwAZ.jpg',
    name: 'The Serpent',
    first_air_date: '2021-01-01',
    overview:
      "The remarkable story of how murderer Charles Sobhraj was captured. As the chief suspect in unsolved murders of young Western travellers across India, Thailand and Nepal’s ‘Hippie Trail’ in 1975 and 1976, Sobhraj had repeatedly slipped from the grasp of authorities worldwide to become Interpol's most wanted man, with arrest warrants on three different continents.",
    vote_count: 8,
    vote_average: 7.6,
    original_name: 'The Serpent',
    origin_country: ['GB'],
    backdrop_path: '/npyVksblzfEiOTf8A1OIgAUJV0N.jpg',
    genre_ids: [18, 80],
    id: 93454,
    popularity: 38.167,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'The Serpent',
    genres: [' Drama', ' Crime'],
  },
  {
    poster_path:
      'https://image.tmdb.org/t/p/w500/1xeiUxShzNn8TNdMqy3Hvo9o2R.jpg',
    original_name: 'Manifest',
    origin_country: ['US'],
    name: 'Manifest',
    overview:
      'After landing from a turbulent but routine flight, the crew and passengers of Montego Air Flight 828 discover five years have passed in what seemed like a few hours. As their new realities become clear, a deeper mystery unfolds and some of the returned passengers soon realize they may be meant for something greater than they ever thought possible.',
    vote_count: 287,
    vote_average: 7.6,
    first_air_date: '2018-09-24',
    id: 79696,
    genre_ids: [18, 9648],
    backdrop_path: '/3ib0uov9Qq9JtTIEGL39irTa3vZ.jpg',
    original_language: 'en',
    popularity: 98.866,
    media_type: 'tv',
    release_date: '2018',
    original_title: 'Manifest',
    genres: [' Drama', ' Mystery'],
  },
  {
    adult: false,
    backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
    genre_ids: [10751, 16, 35, 18, 10402, 14],
    id: 508442,
    title: 'Soul',
    vote_count: 5523,
    vote_average: 8.3,
    video: false,
    release_date: '2020',
    overview:
      'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
    original_title: 'Soul',
    poster_path:
      'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
    original_language: 'en',
    popularity: 922.015,
    media_type: 'movie',
    genres: [' Family', ' Animation', ' Other'],
  },
  {
    vote_average: 7.4,
    overview:
      'Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.',
    release_date: '2021',
    id: 587807,
    adult: false,
    backdrop_path: '/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg',
    genre_ids: [28, 35, 10751],
    vote_count: 1064,
    original_language: 'en',
    original_title: 'Tom & Jerry',
    poster_path:
      'https://image.tmdb.org/t/p/w500/6KErczPBROQty7QoIsaa6wJYXZi.jpg',
    video: false,
    title: 'Tom & Jerry',
    popularity: 2483.116,
    media_type: 'movie',
    genres: [' Action', ' Comedy', ' Other'],
  },
  {
    vote_average: 7.5,
    overview:
      'Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.',
    release_date: '2021',
    id: 567797,
    adult: false,
    backdrop_path: '/sGIfwDYvfU0h1G7pGWEhdEi9hT2.jpg',
    genre_ids: [18, 80, 9648, 53],
    vote_count: 15,
    original_language: 'en',
    original_title: 'The Dry',
    poster_path:
      'https://image.tmdb.org/t/p/w500/zM12bfL2TEqVRXjiQIFUWUMLcCg.jpg',
    video: false,
    title: 'The Dry',
    popularity: 11.225,
    media_type: 'movie',
    genres: [' Drama', ' Crime', ' Other'],
  },
  {
    backdrop_path: '/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg',
    genre_ids: [10765, 16, 10759],
    original_language: 'ja',
    poster_path:
      'https://image.tmdb.org/t/p/w500/aiy35Evcofzl7hASZZvsFgltHTX.jpg',
    vote_count: 3138,
    overview:
      'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
    vote_average: 8.7,
    id: 1429,
    first_air_date: '2013-04-07',
    original_name: '進撃の巨人',
    origin_country: ['JP'],
    name: 'Attack on Titan',
    popularity: 255.007,
    media_type: 'tv',
    release_date: '2013',
    original_title: '進撃の巨人',
    genres: [' Animation'],
  },
  {
    poster_path:
      'https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
    adult: false,
    backdrop_path: '/jMWkd0fuwbG39eJpzycJzPWMCww.jpg',
    id: 399566,
    vote_count: 2694,
    vote_average: 8.6,
    title: 'Godzilla vs. Kong',
    video: false,
    release_date: '2021',
    genre_ids: [28, 878],
    original_language: 'en',
    overview:
      'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    original_title: 'Godzilla vs. Kong',
    popularity: 22934.813,
    media_type: 'movie',
    genres: [' Action', ' Science Fiction'],
  },
  {
    adult: false,
    backdrop_path: '/5NxjLfs7Bi07bfZCRl9CCnUw7AA.jpg',
    genre_ids: [878, 28, 12, 53],
    id: 412656,
    title: 'Chaos Walking',
    vote_count: 83,
    vote_average: 7.3,
    video: false,
    release_date: '2021',
    overview:
      'Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.',
    original_title: 'Chaos Walking',
    poster_path:
      'https://image.tmdb.org/t/p/w500/3W9EpQCVzOfZmeWDMMEiLdtSKSe.jpg',
    original_language: 'en',
    popularity: 257.19,
    media_type: 'movie',
    genres: [' Science Fiction', ' Action', ' Other'],
  },
  {
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    release_date: '2021',
    adult: false,
    backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
    vote_count: 4332,
    genre_ids: [28, 12, 14, 878],
    vote_average: 8.6,
    original_language: 'en',
    original_title: "Zack Snyder's Justice League",
    poster_path:
      'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
    title: "Zack Snyder's Justice League",
    video: false,
    id: 791373,
    popularity: 8408.992,
    media_type: 'movie',
    genres: [' Action', ' Adventure', ' Other'],
  },
  {
    original_name: 'The Falcon and the Winter Soldier',
    origin_country: ['US'],
    backdrop_path: '/JB17sIsU53NuWVUecOwrCA0CUp.jpg',
    id: 88396,
    vote_count: 2587,
    first_air_date: '2021-03-19',
    name: 'The Falcon and the Winter Soldier',
    vote_average: 7.8,
    genre_ids: [10765, 10759, 18],
    poster_path:
      'https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg',
    original_language: 'en',
    overview:
      'Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.',
    popularity: 5223.212,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'The Falcon and the Winter Soldier',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/zii6DDzh0AQMuf9rhAW2L9E1fOi.jpg',
    genre_ids: [18, 37],
    id: 621954,
    original_language: 'en',
    original_title: 'Concrete Cowboy',
    overview:
      'Sent to live with his estranged father for the summer, a rebellious teen finds kinship in a tight-knit Philadelphia community of Black cowboys.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/qRW2poVt06WCVlIhrolWS5af4YV.jpg',
    release_date: '2020',
    title: 'Concrete Cowboy',
    video: false,
    vote_average: 4.9,
    vote_count: 8,
    popularity: 19.433,
    media_type: 'movie',
    genres: [' Drama', ' Western'],
  },
  {
    adult: false,
    backdrop_path: '/nFfXSe79XsJXkkcXZxcQDwbkBm8.jpg',
    genre_ids: [18],
    id: 660006,
    original_language: 'fr',
    original_title: 'Madame Claude',
    overview:
      'Paris, the late 1960s. Madame Claude is at the head of a flourishing business dedicated to prostitution that gives her power over both the french political and criminal worlds. But the end of her empire is closer than she thinks.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wce7KTNGvhYfJqIgtxMhPWrllzg.jpg',
    release_date: '2021',
    title: 'Madame Claude',
    video: false,
    vote_average: 7,
    vote_count: 2,
    popularity: 38.381,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/vx4bevtt3ZVgezPZsuiVxm90l5E.jpg',
    genre_ids: [53, 80],
    id: 651589,
    original_language: 'es',
    original_title: 'Hasta el cielo',
    overview:
      'A commentary on Spanish society dressed as a thriller about the misadventures of a gang of young petty criminals after the real state crash.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/4wBsYozsXBlG7Lx4NO7ycDWnnUs.jpg',
    release_date: '2020',
    title: 'Sky High',
    video: false,
    vote_average: 6.9,
    vote_count: 18,
    popularity: 29.303,
    media_type: 'movie',
    genres: [' Thriller', ' Crime'],
  },
  {
    name: 'Riverdale',
    original_language: 'en',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg',
    id: 69050,
    vote_average: 8.6,
    overview:
      'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    vote_count: 10821,
    first_air_date: '2017-01-26',
    original_name: 'Riverdale',
    origin_country: ['US'],
    backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
    genre_ids: [9648, 18, 80],
    popularity: 1461.366,
    media_type: 'tv',
    release_date: '2017',
    original_title: 'Riverdale',
    genres: [' Mystery', ' Drama', ' Other'],
  },
  {
    vote_average: 8.3,
    overview:
      'A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.',
    release_date: '2021',
    id: 600354,
    adult: false,
    backdrop_path: '/h3weAFgg06GqchI2xDfufBgSFTj.jpg',
    genre_ids: [18],
    vote_count: 146,
    original_language: 'en',
    original_title: 'The Father',
    poster_path:
      'https://image.tmdb.org/t/p/w500/uxWXW1YYQENSv7OzHB4Hds0bK3b.jpg',
    video: false,
    title: 'The Father',
    popularity: 157.379,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    title: 'Wonder Woman 1984',
    vote_average: 6.8,
    overview:
      'A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.',
    release_date: '2020',
    adult: false,
    backdrop_path: '/egg7KFi18TSQc1s24RMmR9i2zO6.jpg',
    vote_count: 4613,
    genre_ids: [14, 28, 12],
    id: 464052,
    original_language: 'en',
    original_title: 'Wonder Woman 1984',
    poster_path:
      'https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
    video: false,
    popularity: 2278.642,
    media_type: 'movie',
    genres: [' Fantasy', ' Action', ' Other'],
  },
  {
    genre_ids: [35, 10749],
    original_language: 'nl',
    original_title: 'Just Say Yes',
    poster_path:
      'https://image.tmdb.org/t/p/w500/7nn4g3RQ5A4p8n3T43UtZdUAOPF.jpg',
    video: false,
    vote_average: 5.7,
    vote_count: 3,
    overview:
      'Incurable romantic Lotte finds her life upended when her plans for a picture-perfect wedding unravel -- just as her self-absorbed sister gets engaged.',
    id: 802504,
    title: 'Just Say Yes',
    release_date: '2021',
    adult: false,
    backdrop_path: '/zUzwNcd3o6yaE5aVHC2G8eCo3qC.jpg',
    popularity: 43.439,
    media_type: 'movie',
    genres: [' Comedy', ' Romance'],
  },
  {
    vote_average: 8.3,
    overview:
      'Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.',
    release_date: '2021',
    id: 527774,
    adult: false,
    backdrop_path: '/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg',
    genre_ids: [16, 12, 14, 10751, 28],
    vote_count: 1943,
    original_language: 'en',
    original_title: 'Raya and the Last Dragon',
    poster_path:
      'https://image.tmdb.org/t/p/w500/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg',
    video: false,
    title: 'Raya and the Last Dragon',
    popularity: 4243.624,
    media_type: 'movie',
    genres: [' Animation', ' Adventure', ' Other'],
  },
  {
    first_air_date: '2021-03-26',
    original_name: 'Invincible',
    origin_country: ['US'],
    overview:
      'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
    backdrop_path: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
    vote_count: 251,
    genre_ids: [16, 10759, 18],
    id: 95557,
    original_language: 'en',
    name: 'Invincible',
    poster_path:
      'https://image.tmdb.org/t/p/w500/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',
    vote_average: 8.8,
    popularity: 546.469,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'Invincible',
    genres: [' Animation', ' Drama'],
  },
  {
    original_name: 'Made For Love',
    origin_country: ['US'],
    genre_ids: [18, 10765, 35],
    id: 90970,
    vote_count: 4,
    first_air_date: '2021-04-01',
    name: 'Made For Love',
    vote_average: 7.5,
    original_language: 'en',
    overview:
      'Thirty-something Hazel Green tries to escape a suffocating marriage — until she realizes her tech billionaire husband has implanted a revolutionary tracking device, the Made for Love, in her brain.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/mfQiuyhFM4Yv98WWV0BTswKG8rM.jpg',
    backdrop_path: '/xKH3vv9sRebArtFTsPJCgX84oEc.jpg',
    popularity: 79.012,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'Made For Love',
    genres: [' Drama', ' Comedy'],
  },
  {
    original_language: 'en',
    poster_path:
      'https://image.tmdb.org/t/p/w500/mZve7vS8S7nyYMIJ5rJrjzOGwAZ.jpg',
    name: 'The Serpent',
    first_air_date: '2021-01-01',
    overview:
      "The remarkable story of how murderer Charles Sobhraj was captured. As the chief suspect in unsolved murders of young Western travellers across India, Thailand and Nepal’s ‘Hippie Trail’ in 1975 and 1976, Sobhraj had repeatedly slipped from the grasp of authorities worldwide to become Interpol's most wanted man, with arrest warrants on three different continents.",
    vote_count: 8,
    vote_average: 7.6,
    original_name: 'The Serpent',
    origin_country: ['GB'],
    backdrop_path: '/npyVksblzfEiOTf8A1OIgAUJV0N.jpg',
    genre_ids: [18, 80],
    id: 93454,
    popularity: 38.167,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'The Serpent',
    genres: [' Drama', ' Crime'],
  },
  {
    poster_path:
      'https://image.tmdb.org/t/p/w500/1xeiUxShzNn8TNdMqy3Hvo9o2R.jpg',
    original_name: 'Manifest',
    origin_country: ['US'],
    name: 'Manifest',
    overview:
      'After landing from a turbulent but routine flight, the crew and passengers of Montego Air Flight 828 discover five years have passed in what seemed like a few hours. As their new realities become clear, a deeper mystery unfolds and some of the returned passengers soon realize they may be meant for something greater than they ever thought possible.',
    vote_count: 287,
    vote_average: 7.6,
    first_air_date: '2018-09-24',
    id: 79696,
    genre_ids: [18, 9648],
    backdrop_path: '/3ib0uov9Qq9JtTIEGL39irTa3vZ.jpg',
    original_language: 'en',
    popularity: 98.866,
    media_type: 'tv',
    release_date: '2018',
    original_title: 'Manifest',
    genres: [' Drama', ' Mystery'],
  },
  {
    adult: false,
    backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
    genre_ids: [10751, 16, 35, 18, 10402, 14],
    id: 508442,
    title: 'Soul',
    vote_count: 5523,
    vote_average: 8.3,
    video: false,
    release_date: '2020',
    overview:
      'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
    original_title: 'Soul',
    poster_path:
      'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
    original_language: 'en',
    popularity: 922.015,
    media_type: 'movie',
    genres: [' Family', ' Animation', ' Other'],
  },
  {
    vote_average: 7.4,
    overview:
      'Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.',
    release_date: '2021',
    id: 587807,
    adult: false,
    backdrop_path: '/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg',
    genre_ids: [28, 35, 10751],
    vote_count: 1064,
    original_language: 'en',
    original_title: 'Tom & Jerry',
    poster_path:
      'https://image.tmdb.org/t/p/w500/6KErczPBROQty7QoIsaa6wJYXZi.jpg',
    video: false,
    title: 'Tom & Jerry',
    popularity: 2483.116,
    media_type: 'movie',
    genres: [' Action', ' Comedy', ' Other'],
  },
  {
    vote_average: 7.5,
    overview:
      'Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.',
    release_date: '2021',
    id: 567797,
    adult: false,
    backdrop_path: '/sGIfwDYvfU0h1G7pGWEhdEi9hT2.jpg',
    genre_ids: [18, 80, 9648, 53],
    vote_count: 15,
    original_language: 'en',
    original_title: 'The Dry',
    poster_path:
      'https://image.tmdb.org/t/p/w500/zM12bfL2TEqVRXjiQIFUWUMLcCg.jpg',
    video: false,
    title: 'The Dry',
    popularity: 11.225,
    media_type: 'movie',
    genres: [' Drama', ' Crime', ' Other'],
  },
  {
    backdrop_path: '/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg',
    genre_ids: [10765, 16, 10759],
    original_language: 'ja',
    poster_path:
      'https://image.tmdb.org/t/p/w500/aiy35Evcofzl7hASZZvsFgltHTX.jpg',
    vote_count: 3138,
    overview:
      'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
    vote_average: 8.7,
    id: 1429,
    first_air_date: '2013-04-07',
    original_name: '進撃の巨人',
    origin_country: ['JP'],
    name: 'Attack on Titan',
    popularity: 255.007,
    media_type: 'tv',
    release_date: '2013',
    original_title: '進撃の巨人',
    genres: [' Animation'],
  },
];
export default arrayAllFilm;
