const arrayAllFilm = [
  {
    poster_path:
      'https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
    adult: false,
    backdrop_path: '/jMWkd0fuwbG39eJpzycJzPWMCww.jpg',
    id: 399566,
    vote_count: 2694,
    vote_average: 8.6,
    title: 'Godzilla vs. Kong',
    video: false,
    release_date: '2021',
    genre_ids: [28, 878],
    original_language: 'en',
    overview:
      'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    original_title: 'Godzilla vs. Kong',
    popularity: 22934.813,
    media_type: 'movie',
    genres: [' Action', ' Science Fiction'],
  },
  {
    adult: false,
    backdrop_path: '/5NxjLfs7Bi07bfZCRl9CCnUw7AA.jpg',
    genre_ids: [878, 28, 12, 53],
    id: 412656,
    title: 'Chaos Walking',
    vote_count: 83,
    vote_average: 7.3,
    video: false,
    release_date: '2021',
    overview:
      'Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.',
    original_title: 'Chaos Walking',
    poster_path:
      'https://image.tmdb.org/t/p/w500/3W9EpQCVzOfZmeWDMMEiLdtSKSe.jpg',
    original_language: 'en',
    popularity: 257.19,
    media_type: 'movie',
    genres: [' Science Fiction', ' Action', ' Other'],
  },
  {
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    release_date: '2021',
    adult: false,
    backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
    vote_count: 4332,
    genre_ids: [28, 12, 14, 878],
    vote_average: 8.6,
    original_language: 'en',
    original_title: "Zack Snyder's Justice League",
    poster_path:
      'https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
    title: "Zack Snyder's Justice League",
    video: false,
    id: 791373,
    popularity: 8408.992,
    media_type: 'movie',
    genres: [' Action', ' Adventure', ' Other'],
  },
  {
    original_name: 'The Falcon and the Winter Soldier',
    origin_country: ['US'],
    backdrop_path: '/JB17sIsU53NuWVUecOwrCA0CUp.jpg',
    id: 88396,
    vote_count: 2587,
    first_air_date: '2021-03-19',
    name: 'The Falcon and the Winter Soldier',
    vote_average: 7.8,
    genre_ids: [10765, 10759, 18],
    poster_path:
      'https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg',
    original_language: 'en',
    overview:
      'Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.',
    popularity: 5223.212,
    media_type: 'tv',
    release_date: '2021',
    original_title: 'The Falcon and the Winter Soldier',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/zii6DDzh0AQMuf9rhAW2L9E1fOi.jpg',
    genre_ids: [18, 37],
    id: 621954,
    original_language: 'en',
    original_title: 'Concrete Cowboy',
    overview:
      'Sent to live with his estranged father for the summer, a rebellious teen finds kinship in a tight-knit Philadelphia community of Black cowboys.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/qRW2poVt06WCVlIhrolWS5af4YV.jpg',
    release_date: '2020',
    title: 'Concrete Cowboy',
    video: false,
    vote_average: 4.9,
    vote_count: 8,
    popularity: 19.433,
    media_type: 'movie',
    genres: [' Drama', ' Western'],
  },
  {
    adult: false,
    backdrop_path: '/nFfXSe79XsJXkkcXZxcQDwbkBm8.jpg',
    genre_ids: [18],
    id: 660006,
    original_language: 'fr',
    original_title: 'Madame Claude',
    overview:
      'Paris, the late 1960s. Madame Claude is at the head of a flourishing business dedicated to prostitution that gives her power over both the french political and criminal worlds. But the end of her empire is closer than she thinks.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wce7KTNGvhYfJqIgtxMhPWrllzg.jpg',
    release_date: '2021',
    title: 'Madame Claude',
    video: false,
    vote_average: 7,
    vote_count: 2,
    popularity: 38.381,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    adult: false,
    backdrop_path: '/vx4bevtt3ZVgezPZsuiVxm90l5E.jpg',
    genre_ids: [53, 80],
    id: 651589,
    original_language: 'es',
    original_title: 'Hasta el cielo',
    overview:
      'A commentary on Spanish society dressed as a thriller about the misadventures of a gang of young petty criminals after the real state crash.',
    poster_path:
      'https://image.tmdb.org/t/p/w500/4wBsYozsXBlG7Lx4NO7ycDWnnUs.jpg',
    release_date: '2020',
    title: 'Sky High',
    video: false,
    vote_average: 6.9,
    vote_count: 18,
    popularity: 29.303,
    media_type: 'movie',
    genres: [' Thriller', ' Crime'],
  },
  {
    name: 'Riverdale',
    original_language: 'en',
    poster_path:
      'https://image.tmdb.org/t/p/w500/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg',
    id: 69050,
    vote_average: 8.6,
    overview:
      'Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.',
    vote_count: 10821,
    first_air_date: '2017-01-26',
    original_name: 'Riverdale',
    origin_country: ['US'],
    backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
    genre_ids: [9648, 18, 80],
    popularity: 1461.366,
    media_type: 'tv',
    release_date: '2017',
    original_title: 'Riverdale',
    genres: [' Mystery', ' Drama', ' Other'],
  },
  {
    vote_average: 8.3,
    overview:
      'A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.',
    release_date: '2021',
    id: 600354,
    adult: false,
    backdrop_path: '/h3weAFgg06GqchI2xDfufBgSFTj.jpg',
    genre_ids: [18],
    vote_count: 146,
    original_language: 'en',
    original_title: 'The Father',
    poster_path:
      'https://image.tmdb.org/t/p/w500/uxWXW1YYQENSv7OzHB4Hds0bK3b.jpg',
    video: false,
    title: 'The Father',
    popularity: 157.379,
    media_type: 'movie',
    genres: [' Drama'],
  },
  {
    title: 'Wonder Woman 1984',
    vote_average: 6.8,
    overview:
      'A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.',
    release_date: '2020',
    adult: false,
    backdrop_path: '/egg7KFi18TSQc1s24RMmR9i2zO6.jpg',
    vote_count: 4613,
    genre_ids: [14, 28, 12],
    id: 464052,
    original_language: 'en',
    original_title: 'Wonder Woman 1984',
    poster_path:
      'https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
    video: false,
    popularity: 2278.642,
    media_type: 'movie',
    genres: [' Fantasy', ' Action', ' Other'],
  }
];

export default arrayAllFilm;
