export default team = [
  {
    name: 'Anna Skorokhod (Ania Walker)',
    position: 'Team Lead/Front-End Developer',
    city: 'Dnipro',
    country: 'Ukraine',
    github: 'https://github.com/AniaWlkr',
    email: 'ania.wlkr@gmail.com',
    smallPhoto: './images/students-modal-pics/Anna_Skorokhod_round.png',
    originalPhoto: './images/students-modal-pics/Anna_Skorokhod_original.jpg',
  },

  {
    name: 'Olha Dolzhenko',
    position: 'Scrum Master/Front-End Developer',
    city: 'Bratislava',
    country: 'Slovakia',
    github: 'https://github.com/OlhaDolzhenko',
    email: 'olyasorokolat@gmail.com',
    smallPhoto: './images/students-modal-pics/Olha_Dolzhenko_round.png',
    originalPhoto: './images/students-modal-pics/Olha_Dolzhenko_original.jpg',
  },

  {
    name: 'Elnara Golovina',
    position: 'Front-End Developer',
    city: 'Kiev',
    country: 'Ukraine',
    github: 'github.com/GolovinaElia',
    email: 'eliagolovina@ukr.net',
    smallPhoto: './images/students-modal-pics/Olha_Dolzhenko_round.png',
    originalPhoto: './images/students-modal-pics/Olha_Dolzhenko_original.jpg',
  },

  {
    name: 'Denys Kostenko',
    position: 'Front-End Developer',
    city: 'Tallinn',
    country: 'Estonia',
    github: 'https://github.com/DenisK0s',
    email: 'kostenkoden89@gmail.com',
    smallPhoto: './images/students-modal-pics/Olha_Dolzhenko_round.png',
    originalPhoto: './images/students-modal-pics/Olha_Dolzhenko_original.jpg',
  },

  {
    name: 'Roma Didukh',
    position: 'Front-End Developer',
    city: 'Brody',
    country: 'Ukraine',
    github: 'https://github.com/didukhroma',
    email: 'didukhroma@gmail.com',
    smallPhoto: './images/students-modal-pics/Roma_Didukh_round.png',
    originalPhoto: './images/students-modal-pics/Roma_Didukh_original.jpg',
  },

  {
    name: 'Igor Oliynik',
    position: 'Front-End Developer',
    city: 'Warsaw',
    country: 'Poland',
    github: 'https://github.com/IgorO-projects',
    email: 'Travis789lee@gmail.com',
    smallPhoto: './images/students-modal-pics/Igor_Oliynik_round.png',
    originalPhoto: './images/students-modal-pics/Igor_Oliynik_original.jpg',
  },

  {
    name: 'Elena Goyeva',
    position: 'Front-End Developer',
    city: 'Lviv',
    country: 'Ukraine',
    github: 'https://github.com/LenaGo1',
    email: 'lena.goyeva@gmail.com',
    smallPhoto: './images/students-modal-pics/Anna_Skorokhod_round.png',
    originalPhoto: './images/students-modal-pics/Anna_Skorokhod_original.jpg',
  },

  {
    name: 'Elena Gubarenko',
    position: 'Front-End Developer',
    city: 'Minsk',
    country: 'Belarus',
    github: 'https://github.com/ElenaGubarenko',
    email: 'N/I',
    smallPhoto: './images/students-modal-pics/Elena_Gubarenko_round.png',
    originalPhoto: './images/students-modal-pics/Elena_Gubarenko_original.jpg',
  },

  {
    name: 'Tatyana Rudenko',
    position: 'Front-End Developer',
    city: 'Kiev',
    country: 'Ukraine',
    github: 'https://github.com/tetrud',
    email: 'rudenkotatyana19@gmail.com',
    smallPhoto: './images/students-modal-pics/Tatyana _Rudenko_round.png',
    originalPhoto: './images/students-modal-pics/Tatyana _Rudenko_original.jpg',
  },
];
